modules:
  - grouping
  - raw_separate
  - exif
input-output:
  input_dir: G:/
  output_dir: E:/Images/2020
raw_separate:
  separate_raw: yes
  raw_dir_name: RAW
grouping:
  year: yes
  month: yes
  months_named: yes
  day: no