modules:
  - grouping
  - raw_separate
  - exif
  - greyscale
input-output:
  input_dir: G:/
  output_dir: E:/Images/2020
raw_separate:
  separate_raw: yes
  raw_dir_name: RAW
grouping:
  year: yes
  month: no
  month_named: no
  day: no
exif:
  artist: Lukas Panni
  copyright: Lukas Panni
greyscale:
  algorithm: average
  file_name: greyscale