name: Pyinstaller build

on:
  push:
    branches: [ master, Exif_editing, dev, release_test ]

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build with Pyinstaller
      run: pyinstaller --onefile image_copy.py
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: image_copy${{runner.os}}
        path: dist/