name: Pyinstaller build

on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    - name: Build with Pyinstaller
      run: |
        cd ImageCopy
        pyinstaller --onefile image_copy.py
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: image_copy${{runner.os}}
        path: ImageCopy/dist/
