name: Pyinstaller build

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Build with Pyinstaller
        run: |
          cd ImageCopy
          pyinstaller --onefile image_copy.py
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: image_copy_${{runner.os}}
          path: ImageCopy/dist/
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2 # download all artifacts
      - run: ls -la

      - run: |
          sudo apt install zip -y
          zip -r image_copy_Linux.zip image_copy_Linux
          zip -r image_copy_Windows.zip image_copy_Windows
          zip -r image_copy_macOS.zip image_copy_macOS

      - name: Release # create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            image_copy_Linux.zip
            image_copy_Windows.zip
            image_copy_macOS.zip

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
